apiVersion: v1
kind: Pod
metadata:
  name: python-http-server
  labels:
    app: pyserver
spec:
  containers:
    - name: pyserver
      image: python:3.9-slim
      command: ["python", "-m", "http.server", "8000"]
      ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: pyserver-service
spec:
  type: NodePort
  selector:
    app: pyserver
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30081
