apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: test-namespace
  project: sample1
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: automation-cluster2
  resourceQuotas:
    pods: "110"
