apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: test1
  project: sample1
spec:
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: cli-with-sharing-rauto-142021595
  resourceQuotas: {}
